kind: Service
apiVersion: v1
metadata:
  name: blog-ui-service
  namespace: blog
  labels:
    app: blog-ui
spec:
  selector:
    app: blog-ui
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30082
    name: http
  type: NodePort
---
apiVersion: gateway.cloud.ik.am/v1beta1
kind: RouteDefinition
metadata:
  name: blog-ui
  namespace: blog
spec:
  serviceName: blog-ui-service
  route:
    predicates:
      - Host=blog.ik.am
    filters:
      - RequestLogging=
      - SetResponseHeader=Access-Control-Allow-Origin, *
      - SetResponseHeader=Access-Control-Allow-Methods, GET, OPTIONS
      - SetResponseHeader=Access-Control-Max-Age, 3600
      - SetResponseHeader=Access-Control-Allow-Headers, *
      - name: Retry
        args:
          retries: "3"
          statuses: BAD_GATEWAY
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog-ui
  namespace: blog
  labels:
    app: blog-ui
spec:
  replicas: 2
  revisionHistoryLimit: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blog-ui
      annotations:
        kubernetes.io/change-cause: "FIXME"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /actuator/prometheus
    spec:
      containers:
      - name: blog-ui
        image: asia.gcr.io/fe-tmaki/blog-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: _JAVA_OPTIONS
          value: "-Duser.timezone=Asia/Tokyo -Duser.language=en -Dinfo.docker.digest=INFO_DOCKER_DIGEST"
        - name: SPRING_ZIPKIN_SERVICE_NAME
          value: "${INFO_K8S_NAMESPACE}:blog-ui"
        - name: SPRING_SECURITY_USER_NAME
          valueFrom:
            secretKeyRef:
              name: blog-config-secret
              key: ops-username
        - name: SPRING_SECURITY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog-config-secret
              key: ops-password
        - name: INFO_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INFO_K8S_POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INFO_K8S_APP
          value: "${spring.application.name}"
        - name: MANAGEMENT_METRICS_TAGS_NAMESPACE
          value: "${INFO_K8S_NAMESPACE}"
        - name: MANAGEMENT_METRICS_TAGS_POD
          value: "${INFO_K8S_POD}"
        - name: MANAGEMENT_METRICS_TAGS_APP
          value: "${INFO_K8S_APP}"
        volumeMounts:
        - name: tmp
          mountPath: /home/vcap/tmp
        resources:
          limits:
            memory: "300Mi"
          requests:
            memory: "300Mi"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
      affinity:
         podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             - labelSelector:
                 matchExpressions:
                   - key: "app"
                     operator: In
                     values:
                     - blog-ui
               topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: tmp
        emptyDir: {}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: blog-ui
  namespace: blog
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: blog-ui
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: blog-ui
  name: blog-ui
  namespace: blog
spec:
  endpoints:
    - interval: 30s
      port: http
      path: /actuator/prometheus
      basicAuth:
        username:
          name: blog-config-secret
          key: ops-username
        password:
          name: blog-config-secret
          key: ops-password
  namespaceSelector:
    matchNames:
      - blog
  selector:
    matchLabels:
      app: blog-ui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: blog
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: blog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring