kind: Service
apiVersion: v1
metadata:
  name: blog-ui-service
  namespace: blog
  labels:
    app: blog-ui
spec:
  selector:
    app: blog-ui
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30082
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog-ui
  namespace: blog
  labels:
    app: blog-ui
spec:
  replicas: 2
  revisionHistoryLimit: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blog-ui
      annotations:
        kubernetes.io/change-cause: "FIXME"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /actuator/prometheus
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: blog-ui
        image: harbor-13-78-118-111.sslip.io/categolj/blog-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: _JAVA_OPTIONS
          value: "-Xmx78M -Xss1M -XX:MaxMetaspaceSize=80M -XX:ReservedCodeCacheSize=16M -XX:CompressedClassSpaceSize=20M -XX:MaxDirectMemorySize=32M -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Duser.timezone=Asia/Tokyo -Duser.language=en -Dinfo.docker.digest=INFO_DOCKER_DIGEST"
        - name: SPRING_SECURITY_USER_NAME
          valueFrom:
            secretKeyRef:
              name: blog-config-secret
              key: ops-username
        - name: SPRING_SECURITY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog-config-secret
              key: ops-password
        - name: SPRING_SLEUTH_WEB_ADDITIONAL_SKIP_PATTERN
          value: /actuator.*
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
      affinity:
         podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             - labelSelector:
                 matchExpressions:
                   - key: "app"
                     operator: In
                     values:
                     - blog-ui
               topologyKey: "kubernetes.io/hostname"
